Title =  "Loving life and dreams."
#BaseUrl = "https://antonio-dc.gitee.io/"


DefaultContentLanguage = "zh-cn"
LanguageCode = "zh-CN"

Theme =  "hugo-theme-next"

MetaDataFormat =  "toml"

PaginatePath =  "p"
Paginate = 5

DisablePathToLower =  false

PreserveTaxonomyNames = false

PygmentsStyle = "emacs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true

timeout = 100000
ignoreErrors = ["error-remote-getjson"]

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/xml"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false


[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true
  [markup.tableOfContents]
    endLevel = 7
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4


