[[Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Main]]
  Name = "归档"
  Pre = "archive"
  URL = "post"
  Weight = 2
[[Main]]
  Name = "专栏"
  Pre = "book"
  URL = "series"
  Weight = 3
[[Main]]
  Name = "友链"
  Pre = "heartbeat"
  URL = "friend.html"
  Weight = 4
[[Main]]
  Name = "关于"
  Pre = "user"
  URL = "about.html"
  Weight = 5