[[Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "post"
  Weight = 2
[[Main]]
  Name = "Reviews"
  Pre = "book"
  URL = "series"
  Weight = 3
[[Main]]
  Name = "Friend"
  Pre = "heartbeat"
  URL = "friend.html"
  Weight = 4
[[Main]]
  Name = "User"
  Pre = "user"
  URL = "about.html"
  Weight = 5