Description = "Weclome to Elkan's blog site that who is best on program develop, pre-sales and big data."
Keywords =  "Blog, Software, Big Data, Product, Architecture, Java, Kylin"
Subtitle = "Don't stop running forward!"
AuthorImg = "/img/avatar.jpg"
AuthorName = "Antonio.DC"
Introduce = "You only live once!"
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"
Notice = "欢迎来到我的博客"

[Footer]
  StorageLink = "https://www.ucloud.cn/"
  StorageName = "UCloud Storage"
  ICPLink = "http://beian.miit.gov.cn"
  ICPNo = "ICP.NO 18047355"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/AntonioDC-AAA"

[[Socials]]
  Name = "Gitee"
  Icon = "globe"
  URL = "https://gitee.com/antonio-dc"

[[Links]]
  Name = "Martinfowler"
  Permalink = "https://martinfowler.com/"

[[Links]]
  Name = "LiaoXueFeng"
  Permalink = "https://www.liaoxuefeng.com/"

[[Links]]
  Name = "Golang"
  Permalink = "https://golang.google.cn/"

[[Links]]
  Name = "JAVA"
  Permalink = "https://www.oracle.com/java/"