Description = "欢迎来到凡梦星尘空间站，个人主要专注于程序开发，产品，售前及大数据解决方案。"
Keywords =  "博客, 程序员, 架构师, 思考, 读书, 笔记, 技术, 分享, 大数据, 产品"
Subtitle = "没有伞的孩子要学会努力奔跑!"
AuthorImg = "/img/avatar.jpg"
AuthorName = "Antonio.DC"
Introduce = "You only live once!"
DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"
Notice = "欢迎来到我的博客"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/AntonioDC-AAA"

[[Socials]]
  Name = "Gitee"
  Icon = "globe"
  URL = "https://gitee.com/antonio-dc"

[[Links]]
  Name = "马丁福勒"
  Permalink = "https://martinfowler.com/"

[[Links]]
  Name = "廖雪峰"
  Permalink = "https://www.liaoxuefeng.com/"

[[Links]]
  Name = "Golang"
  Permalink = "https://golang.google.cn/"

[[Links]]
  Name = "JAVA"
  Permalink = "https://www.oracle.com/java/"

